[package]
name = "sleepy"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.12" }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4" }
